server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 0

mybatis:
  mapper-locations: classpath*:mapper/*.xml

grpc:
  server:
    port: 9898

logging:
  level:
    root: INFO   # 默认日志级别
    com.example.mallserver: DEBUG  # 为您的应用程序设置DEBUG日志级别
    org.springframework: DEBUG    # 为Spring框架设置DEBUG日志级别

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  isReadCookie: false